version: "3.9"
services:
  app:
    image: gnikk/mts-credit:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mts-credit
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
  db:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mts-credit
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: